//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridView
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> NumberShipped { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        public virtual product product { get; set; }
    }
}
